### ISSUE TITLE
Black Tangent seems to no longer exist

### ISSUE THREAD

**Issue by raja-baz** [remoteintech/remote-jobs#792] opened 2020-08-19 12:27 UTC
Black Tangent is listed but all of the links in the document are broken and even searching for the company seems to only turn up things that no longer exist.

**Comment by dopecodez** [comment] 2020-10-15 14:35
I checked the same, and looks like the issue is right. Black tangent does not seem to exist at all.

Raised a PR for housekeeping.

**Comment by dougaitken** [comment] 2020-10-19 18:36
Fixed in #810

**Closed by dougaitken** 2020-10-19 18:36 UTC
Labels: enhancement, housekeeping
