### ISSUE TITLE
Create a proper new beautiful looking navbar and other ui desgins

### ISSUE THREAD

**Issue by amrit1004** [remoteintech/remote-jobs#1856] opened 2024-10-17 18:37 UTC
PLEASE OPEN A NEW DISCUSSION.

[Discussions > New > Ideas](https://github.com/remoteintech/remote-jobs/discussions/new?category=ideas)

**Comment by Zinkeng** [comment] 2024-10-21 11:18
Interested

**Comment by dougaitken** [comment] 2024-12-27 19:04
Dupe of #1835

**Closed by dougaitken** 2024-12-27 19:04 UTC
